---
- name: Listen for messages on a kafka topic
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 192.168.1.14
        port: 9092
        topic: my-topic
        group_id: ansible-eda
        
  rules:
    - name: ALl in one Solution
      condition: event.body.message == ""
      action:
        run_job_template:
          name: do-something
          organization: Default

    - name: R2 - Didn't hear "Hello!"
      condition: event.body.message is defined and event.body.message != "Hello!"
      action:
        debug:
          msg: "You said, '{{ event.body.message }}'. Is that what you meant to say?"

    - name: R3 - Debug
      condition: event.meta is defined
      action:
        debug:
