- name: Configure webserver with nginx
  hosts: all
  become: True
  tasks:
    - name: resttarting nginx on "{{inventory_hostname}}"
      service:
        name: nginx 
        state: restarted
        enabled: true
        
    - name: Genrate Email content
      ansible.builtin.template:
        src: alert_email_html.j2
        dest: /tmp/alert_email.html
      run_once: true  
      delegate_to: 127.0.0.1        
        
    - name: Send email notification
      mail:
        host: smtp.gmail.com
        port: 587
        subtype: html
        to:
        - "nrathi@redhat.com"
        subject: "Alert: Nginx is restarted on {{inventory_hostname}}"
        body: "{{ lookup('file', '/tmp/alert_email.html') }}"
        username: dmeonavneet@gmail.com
        password: "rbfqhoincpyouxqk"
      run_once: true  
      delegate_to: 127.0.0.1  
