---
- name: Create Directory and files
  hosts: all
  # connection: local
  gather_facts: false
  vars:
    destination_folder:
        - /home/krsy/data_repo/dest1
        - /home/krsy/data_repo/dest2
        - /home/krsy/data_repo/dest3
        - /home/krsy/data_repo/dest4
  tasks:
    - name: Ensure the directory /example/directory exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ destination_folder }}"
      ignore_errors: True
   
    - name: Add data to a file
      copy:
        dest: "{{ item + '/' + ansible_eda.event.meta.received_at.rstrip('Z')}}"
        content: "{{ ansible_eda.event }}"
      loop: "{{ destination_folder }}"
      ignore_errors: True
